require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/react-native-unimodules/cocoapods.rb'

platform :ios, '10.0'

target 'procrastinationExpoRN' do
  config = use_native_modules!
  use_unimodules!
  use_react_native!(:path => config["reactNativePath"])
end
