export const FETCH_ANSWERS = 'FETCH_ANSWERS';
export const FETCH_COUNTERS = 'FETCH_COUNTERS';
export const FETCH_HISTORY = 'FETCH_HISTORY';
export const FETCH_SETTINGS = 'FETCH_SETTINGS';
export const SET_LOADING = 'SET_LOADING';
export const WELCOME_USER = 'WELCOME_USER';
export const HIDDEN_FEATURES = 'HIDDEN_FEATURES';
export const FIRST_NOTIFICATION = 'FIRST_NOTIFICATION';
